language: go
os:
  - windows
  - linux

go:
  - tip

 before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

env:
  - CODECOV_TOKEN="4e562029-c6af-4c79-b362-687fdaa05bc7"

after_success:
  - bash <(curl -s https://codecov.io/bash)